### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Carambarass** [rogeraabbccdd/Music-Kits#19]
Hello.
Found two problems with the plugin.
1. The latest music kit are not selected normally. You choose one and the other is taken.
2. Saving music sets does not work. After exiting and entering in game, the standard is returned.
I really liked this plugin, it would be good to fix it.
Sorry to my bad english(

**Comment by crashzk** [comment]
@Carambarass are you testing with the latest version?

https://github.com/rogeraabbccdd/Music-Kits/archive/refs/heads/master.zip

I'm using it, haven't seen BUGS yet in the case.

**Comment by YongkyA23** [comment]
@crashzk i have used the one that u send, music kit still not saved

**Comment by crashzk** [comment]
> @crashzk usei aquele que você enviou, kit de música ainda não salvo

Really, I checked here, I select the music kits normally, however, when changing the map, it is not saved.

I'll see if I can fix it.

**Comment by Renal8bits** [comment]
Hello! Have somebody fixed the bug with music kits not saving?

**Comment by rogeraabbccdd** [comment]
Fixed in https://github.com/rogeraabbccdd/Music-Kits/commit/69ef667f1b989682e210dfa9b65c0da59cd4ffbc.
