### ISSUE TITLE
 [ SUGGESTED ] - Privileges of ADMIN

### ISSUE THREAD

**Issue by paulocrash** [rogeraabbccdd/Music-Kits#2]
You could add flag in the plugin to let only those who wanted to give us the privileges to access the Menu Music kit.

Alas in the case the people that were going to select which flag to by in the config to have access.

**Comment by rogeraabbccdd** [comment]
use admin_overrides.cfg

**Comment by paulocrash** [comment]
I made the change in the .sp file as you mentionedç.

> 	HookEvent("player_spawn", Event_Player_Spawn, EventHookMode_Pre);
> 	HookEvent("player_disconnect", Event_Disc);
> 	RegConsoleCmd("sm_music", Music, ADMFLAG_CUSTOM3, "Set Music in Game");
> 	RegConsoleCmd("sm_musickit", Music, ADMFLAG_CUSTOM3, "Set Music in Game");
> 	RegConsoleCmd("sm_mk", Music, ADMFLAG_CUSTOM3, "Set Music in Game");
> 

It only gives the following error when compiling:
![2017-03-12](https://cloud.githubusercontent.com/assets/20426000/23839529/6be36f56-077d-11e7-8167-f328b40c6cbb.png)

**Comment by rogeraabbccdd** [comment]
RegAdminCmd("sm_music", Music,  ADMFLAG_CUSTOM3, "Set Music in Game.");

**Comment by paulocrash** [comment]
Could you send me your include so you can compile I put the morecolors.inc of the internet even though it buga the colors.

**Comment by rogeraabbccdd** [comment]
https://github.com/rogeraabbccdd/Kento-Rankme/blob/master/gameserver/scripting/include/kento_csgocolors.inc
