### ISSUE TITLE
Update New Music Kit

### ISSUE THREAD

**Issue by paulocrash** [rogeraabbccdd/Music-Kits#4]
Would it be possible to update the plugin to add the new music kit that came out in the last CSGO update?

https://blog.counter-strike.net/index.php/2019/03/23717/

**Comment by LemonPAKA** [comment]
> Would it be possible to update the plugin to add the new music kit that came out in the last CSGO update?
> 
> https://blog.counter-strike.net/index.php/2019/03/23717/

I forked this and updated EZ4ENCE music kit...if you need it just download it

**Comment by rogeraabbccdd** [comment]
pull requests are welcome.

**Comment by paulocrash** [comment]
Done https://github.com/rogeraabbccdd/Music-Kits/pull/5, I hope everything is right, my first PR. : )

@rogeraabbccdd

**Comment by LemonPAKA** [comment]
> pull requests are welcome.

searching how to use pull requests.....I am new in github

**Comment by rogeraabbccdd** [comment]
#6 is merged
